param(
    [string]$InputPath = "",
    [string]$RuntimeRoot = "",
    [switch]$CreatePackage
)

$ErrorActionPreference = "Stop"

function Resolve-FullPath {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return ""
    }

    if (Test-Path -LiteralPath $Path) {
        return (Resolve-Path -LiteralPath $Path).Path
    }

    return [System.IO.Path]::GetFullPath($Path)
}

function Resolve-RuntimeRoot {
    param([string]$RequestedRuntimeRoot)

    if (-not [string]::IsNullOrWhiteSpace($RequestedRuntimeRoot)) {
        return Resolve-FullPath $RequestedRuntimeRoot
    }

    $scriptRoot = Split-Path -Parent $PSCommandPath
    $candidate = Split-Path -Parent $scriptRoot
    return Resolve-FullPath $candidate
}

function Resolve-LatestPackage {
    param(
        [string]$RequestedInputPath,
        [string]$RuntimeRootPath
    )

    if (-not [string]::IsNullOrWhiteSpace($RequestedInputPath)) {
        return Resolve-FullPath $RequestedInputPath
    }

    $packageRoot = Join-Path $RuntimeRootPath "DebugPackages"
    if (-not (Test-Path -LiteralPath $packageRoot -PathType Container)) {
        throw "DebugPackages folder not found: $packageRoot"
    }

    $latest = Get-ChildItem -LiteralPath $packageRoot -Filter "GoblinFarmer_Debug_*.zip" -File -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 1
    if ($null -eq $latest) {
        throw "No GoblinFarmer_Debug_*.zip packages found in $packageRoot"
    }

    return $latest.FullName
}

function Get-PackageRoot {
    param(
        [string]$Path,
        [string]$TempRoot
    )

    if (Test-Path -LiteralPath $Path -PathType Container) {
        return Resolve-FullPath $Path
    }

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Input path not found: $Path"
    }

    if ([System.IO.Path]::GetExtension($Path) -ne ".zip") {
        throw "Input path must be a debug package ZIP or extracted package folder: $Path"
    }

    New-Item -ItemType Directory -Path $TempRoot -Force | Out-Null
    Expand-Archive -LiteralPath $Path -DestinationPath $TempRoot -Force
    return $TempRoot
}

function Add-Section {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Title
    )

    $Lines.Add("")
    $Lines.Add($Title)
    $Lines.Add(("-" * $Title.Length))
}

function Add-FileList {
    param(
        [System.Collections.Generic.List[string]]$Lines,
        [string]$Title,
        [System.IO.FileInfo[]]$Files,
        [int]$Limit = 20
    )

    Add-Section $Lines $Title
    if ($Files.Count -eq 0) {
        $Lines.Add("none")
        return
    }

    foreach ($file in $Files | Select-Object -First $Limit) {
        $Lines.Add($file.FullName)
    }
    if ($Files.Count -gt $Limit) {
        $Lines.Add("... $($Files.Count - $Limit) more")
    }
}

$runtimeRootPath = Resolve-RuntimeRoot $RuntimeRoot
$input = Resolve-LatestPackage $InputPath $runtimeRootPath
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) "GoblinFarmerReplayCli_$timestamp"
$logRoot = Join-Path $runtimeRootPath "Logs"
$summaryPath = Join-Path $logRoot "GoblinReplayCli_$timestamp.txt"
New-Item -ItemType Directory -Path $logRoot -Force | Out-Null

try {
    $packageRoot = Get-PackageRoot $input $tempRoot
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("Goblin replay CLI summary")
    $lines.Add("CreatedLocal=$(Get-Date -Format O)")
    $lines.Add("RuntimeRoot=$runtimeRootPath")
    $lines.Add("InputPath=$input")
    $lines.Add("PackageRoot=$packageRoot")
    $lines.Add("Mode=PackageArtifactReview")
    $lines.Add("Note=Full image-template replay is generated by the VS Debug Create Debug Package button; this CLI reviews the packaged replay artifacts and decision evidence.")

    $manifest = @(Get-ChildItem -LiteralPath $packageRoot -Filter "debug-package-manifest.txt" -File -ErrorAction SilentlyContinue)
    $reviewIndex = @(Get-ChildItem -LiteralPath $packageRoot -Filter "goblin-tracker-review.html" -File -ErrorAction SilentlyContinue)
    $trackerSummaries = @(Get-ChildItem -LiteralPath $packageRoot -Filter "goblin-tracker-summary.txt" -File -ErrorAction SilentlyContinue)
    $replayLogs = @(Get-ChildItem -LiteralPath $packageRoot -Recurse -Filter "GoblinReplay_*.log" -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending)
    $replayReports = @(Get-ChildItem -LiteralPath $packageRoot -Recurse -Filter "GoblinReplay_*.html" -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending)
    $replaySummaries = @(Get-ChildItem -LiteralPath $packageRoot -Recurse -Filter "GoblinReplay_*_summary.txt" -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending)
    $changedSummaries = @(Get-ChildItem -LiteralPath $packageRoot -Recurse -Filter "GoblinReplay_*_changed.txt" -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending)
    $decisionBundles = @(Get-ChildItem -LiteralPath $packageRoot -Recurse -Filter "decision.txt" -File -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName.Replace('/', '\').IndexOf('\GoblinReplay_', [System.StringComparison]::OrdinalIgnoreCase) -ge 0 })
    $evidenceImages = @(Get-ChildItem -LiteralPath $packageRoot -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName.Replace('/', '\').IndexOf('\Debug\GoblinEvidence\', [System.StringComparison]::OrdinalIgnoreCase) -ge 0 -and $_.Extension -match '^\.(png|jpg|jpeg|bmp)$' })

    Add-Section $lines "Artifact counts"
    $lines.Add("Manifest=$($manifest.Count)")
    $lines.Add("ReviewIndex=$($reviewIndex.Count)")
    $lines.Add("TrackerSummaries=$($trackerSummaries.Count)")
    $lines.Add("ReplayLogs=$($replayLogs.Count)")
    $lines.Add("ReplayHtmlReports=$($replayReports.Count)")
    $lines.Add("ReplaySummaries=$($replaySummaries.Count)")
    $lines.Add("ChangedDecisionSummaries=$($changedSummaries.Count)")
    $lines.Add("DecisionBundles=$($decisionBundles.Count)")
    $lines.Add("EvidenceImages=$($evidenceImages.Count)")

    Add-FileList $lines "Review entry points" @($reviewIndex + $trackerSummaries + $manifest) 20
    Add-FileList $lines "Replay HTML reports" $replayReports 20
    Add-FileList $lines "Changed-decision summaries" $changedSummaries 20
    Add-FileList $lines "Per-observation bundles" $decisionBundles 30

    if ($changedSummaries.Count -gt 0) {
        Add-Section $lines "Latest changed-decision preview"
        foreach ($line in Get-Content -LiteralPath $changedSummaries[0].FullName | Select-Object -First 80) {
            $lines.Add($line)
        }
    }

    if ($trackerSummaries.Count -gt 0) {
        Add-Section $lines "Tracker summary preview"
        foreach ($line in Get-Content -LiteralPath $trackerSummaries[0].FullName | Select-Object -First 80) {
            $lines.Add($line)
        }
    }

    $lines | Out-File -FilePath $summaryPath -Encoding utf8
    Write-Host "Goblin replay CLI summary: $summaryPath"

    if ($CreatePackage) {
        $packageScript = Join-Path (Split-Path -Parent $PSCommandPath) "create-debug-package.ps1"
        if (-not (Test-Path -LiteralPath $packageScript -PathType Leaf)) {
            throw "Cannot create package; script missing: $packageScript"
        }

        & $packageScript -RuntimeRoot $runtimeRootPath
    }
}
finally {
    if (Test-Path -LiteralPath $tempRoot) {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force
    }
}
